language: php

php:
  - '5.6'
  - '7.0'

before_install:
    - cd test
    - composer install
    - php vendor/bin/codecept build

script:
    - php vendor/bin/codecept run unit --debug --coverage
    - php vendor/bin/codecept run acceptance --debug --skip-group staging
    - php vendor/bin/codecept run acceptance --debug --env staging --group staging
